/** 
	Request Format:
	tag: Tag containing the request type / action.
	url: String containing the url to the search page for the individual prof.
	name: String containing the prof name.
**/
function rmpSearchRequest(request, sender, sendResponse) {
	$.get(request.url, function(outterData){
		var profLink = $($($.parseHTML(outterData)).find('.listings')).find('a:first').attr('href')
		if(profLink) {
			profLink = 'http://www.ratemyprofessors.com' + profLink

			$.get(profLink, function(innerData) {
				overallGrade = $($.parseHTML(innerData)).find('.grade:first').html()
				sendResponse({link: profLink, name: request.name, overallGrade: overallGrade})
			}).fail(function() {
				//This is theoretically impossible, since this link is generated by RMP's website, this should never happen. Oh well handle anyway.
				sendResponse(null)
			})







			
		}
	}).fail(function(){
		sendResponse(null)
	})
}

chrome.runtime.onMessage.addListener(
  function(request, sender, sendResponse) {
    if (request.tag == 'fetch_rmp_data') {
      	rmpSearchRequest(request, sender, sendResponse)
      	return true;
    } else {
    	chrome.pageAction.show(sender.tab.id);
    	sendResponse();
    }
  });